//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.NetworkAcceleration
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugins.NetworkAcceleration.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Optimization.
        /// </summary>
        public static string NetworkAcceleration_DnsOptimization {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DnsOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligently resolves optimal domain IP addresses based on network conditions, solving DNS pollution issues.
        /// </summary>
        public static string NetworkAcceleration_DnsOptimizationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DnsOptimizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically selects the fastest DNS server for domain name resolution, improving access speed..
        /// </summary>
        public static string NetworkAcceleration_DnsOptimizationEnabledDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DnsOptimizationEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Acceleration.
        /// </summary>
        public static string NetworkAcceleration_GithubAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_GithubAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub direct connection acceleration, including Release, Clone, Raw downloads, etc..
        /// </summary>
        public static string NetworkAcceleration_GithubAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_GithubAccelerationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GitHub acceleration to improve GitHub access speed, including code cloning, file downloads, etc..
        /// </summary>
        public static string NetworkAcceleration_GithubAccelerationEnabledDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_GithubAccelerationEnabledDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub acceleration for faster access.
        /// </summary>
        public static string NetworkAcceleration_GithubAccelerationShortDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_GithubAccelerationShortDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steam Acceleration.
        /// </summary>
        public static string NetworkAcceleration_SteamAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_SteamAcceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steam platform acceleration for faster downloads and updates.
        /// </summary>
        public static string NetworkAcceleration_SteamAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_SteamAccelerationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steam acceleration for faster downloads.
        /// </summary>
        public static string NetworkAcceleration_SteamAccelerationShortDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_SteamAccelerationShortDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discord Acceleration.
        /// </summary>
        public static string NetworkAcceleration_DiscordAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DiscordAcceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discord platform acceleration for faster downloads and updates.
        /// </summary>
        public static string NetworkAcceleration_DiscordAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DiscordAccelerationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discord acceleration for faster downloads.
        /// </summary>
        public static string NetworkAcceleration_DiscordAccelerationShortDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_DiscordAccelerationShortDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NPM Acceleration.
        /// </summary>
        public static string NetworkAcceleration_NpmAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_NpmAcceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NPM registry acceleration for faster package downloads.
        /// </summary>
        public static string NetworkAcceleration_NpmAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_NpmAccelerationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NPM acceleration for faster downloads.
        /// </summary>
        public static string NetworkAcceleration_NpmAccelerationShortDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_NpmAccelerationShortDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Python Acceleration.
        /// </summary>
        public static string NetworkAcceleration_PythonAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PythonAcceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Python package index acceleration for faster pip installations.
        /// </summary>
        public static string NetworkAcceleration_PythonAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PythonAccelerationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Python acceleration for faster downloads.
        /// </summary>
        public static string NetworkAcceleration_PythonAccelerationShortDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PythonAccelerationShortDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Acceleration.
        /// </summary>
        public static string NetworkAcceleration_PageTitle {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time network acceleration and optimization features, including DNS optimization, request interception, and proxy acceleration..
        /// </summary>
        public static string NetworkAcceleration_PageDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string NetworkAcceleration_ProxySettings {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure network proxy server settings.
        /// </summary>
        public static string NetworkAcceleration_ProxySettingsDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxySettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Address:. 
        /// </summary>
        public static string NetworkAcceleration_ProxyAddress {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 127.0.0.1:7890.
        /// </summary>
        public static string NetworkAcceleration_ProxyAddressPlaceholder {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxyAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure local proxy server address and port. Leave blank for default settings..
        /// </summary>
        public static string NetworkAcceleration_ProxyAddressDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxyAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Interception.
        /// </summary>
        public static string NetworkAcceleration_RequestInterception {
            get {
                return ResourceManager.GetString("NetworkAcceleration_RequestInterception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercepts inaccessible websites and proxies to accelerated mirror sites.
        /// </summary>
        public static string NetworkAcceleration_RequestInterceptionDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_RequestInterceptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically proxies inaccessible website requests to available accelerated mirror sites..
        /// </summary>
        public static string NetworkAcceleration_RequestInterceptionEnabledDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_RequestInterceptionEnabledDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform Acceleration.
        /// </summary>
        public static string NetworkAcceleration_PlatformAcceleration {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PlatformAcceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform-specific acceleration features for optimal performance.
        /// </summary>
        public static string NetworkAcceleration_PlatformAccelerationDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_PlatformAccelerationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service Status.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatus {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running status of network acceleration service.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatusDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatusRunning {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatusStopped {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network acceleration service is running, providing you with acceleration services.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatusRunningDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatusRunningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network acceleration service is currently not running.
        /// </summary>
        public static string NetworkAcceleration_ServiceStatusStoppedDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ServiceStatusStoppedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Traffic.
        /// </summary>
        public static string NetworkAcceleration_AcceleratedTraffic {
            get {
                return ResourceManager.GetString("NetworkAcceleration_AcceleratedTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string NetworkAcceleration_Downloaded {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string NetworkAcceleration_Uploaded {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Traffic.
        /// </summary>
        public static string NetworkAcceleration_TotalTraffic {
            get {
                return ResourceManager.GetString("NetworkAcceleration_TotalTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string NetworkAcceleration_ResetStatistics {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ResetStatistics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string NetworkAcceleration_ResetStatisticsButton {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ResetStatisticsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate Setup Failed.
        /// </summary>
        public static string NetworkAcceleration_Error_CertificateSetupFailed {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_CertificateSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to setup root certificate, please check permissions.
        /// </summary>
        public static string NetworkAcceleration_Error_CertificateSetupFailedDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_CertificateSetupFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Service Startup Failed.
        /// </summary>
        public static string NetworkAcceleration_Error_ProxyServiceStartupFailed {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_ProxyServiceStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start reverse proxy service.
        /// </summary>
        public static string NetworkAcceleration_Error_ProxyServiceStartupFailedDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_ProxyServiceStartupFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Failed.
        /// </summary>
        public static string NetworkAcceleration_Error_StartupFailed {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while starting service: {0}.
        /// </summary>
        public static string NetworkAcceleration_Error_StartupFailedDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_StartupFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Failed.
        /// </summary>
        public static string NetworkAcceleration_Error_StopFailed {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_StopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while stopping service: {0}.
        /// </summary>
        public static string NetworkAcceleration_Error_StopFailedDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Error_StopFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Chart.
        /// </summary>
        public static string NetworkAcceleration_TrafficChart {
            get {
                return ResourceManager.GetString("NetworkAcceleration_TrafficChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Real-time Traffic Statistics and Trend Analysis.
        /// </summary>
        public static string NetworkAcceleration_TrafficStatistics {
            get {
                return ResourceManager.GetString("NetworkAcceleration_TrafficStatistics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Real-time display of download and upload speed changes.
        /// </summary>
        public static string NetworkAcceleration_TrafficChartDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_TrafficChartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        public static string NetworkAcceleration_ConnectionTimeout {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ConnectionTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection timeout in seconds.
        /// </summary>
        public static string NetworkAcceleration_ConnectionTimeoutDescription {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ConnectionTimeoutDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proxy Port.
        /// </summary>
        public static string NetworkAcceleration_ProxyPort {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxyPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g., 7890.
        /// </summary>
        public static string NetworkAcceleration_ProxyPortPlaceholder {
            get {
                return ResourceManager.GetString("NetworkAcceleration_ProxyPortPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string NetworkAcceleration_Platform_GitHub {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Platform_GitHub", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string NetworkAcceleration_Platform_Steam {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Platform_Steam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string NetworkAcceleration_Platform_Discord {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Platform_Discord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to npm.
        /// </summary>
        public static string NetworkAcceleration_Platform_Npm {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Platform_Npm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PyPI.
        /// </summary>
        public static string NetworkAcceleration_Platform_PyPI {
            get {
                return ResourceManager.GetString("NetworkAcceleration_Platform_PyPI", resourceCulture);
            }
        }
    }
}
