//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugins.ViveTool.Resources
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugins.ViveTool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool.
        /// </summary>
        public static string ViveTool_PageTitle {
            get {
                return ResourceManager.GetString("ViveTool_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Windows feature flags using ViVeTool. Enable or disable experimental Windows features..
        /// </summary>
        public static string ViveTool_PageDescription {
            get {
                return ResourceManager.GetString("ViveTool_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ViveTool_WarningTitle {
            get {
                return ResourceManager.GetString("ViveTool_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying Windows feature flags can affect system stability. Use with caution. Some changes may require a system restart to take effect..
        /// </summary>
        public static string ViveTool_WarningMessage {
            get {
                return ResourceManager.GetString("ViveTool_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool Status.
        /// </summary>
        public static string ViveTool_ViveToolStatus {
            get {
                return ResourceManager.GetString("ViveTool_ViveToolStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool found at: {0}.
        /// </summary>
        public static string ViveTool_ViveToolFound {
            get {
                return ResourceManager.GetString("ViveTool_ViveToolFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool not found. Please download vivetool.exe and place it in the plugin directory or system PATH..
        /// </summary>
        public static string ViveTool_ViveToolNotFound {
            get {
                return ResourceManager.GetString("ViveTool_ViveToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking ViVeTool status.
        /// </summary>
        public static string ViveTool_ViveToolError {
            get {
                return ResourceManager.GetString("ViveTool_ViveToolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: {0} / {1} ({2}%).
        /// </summary>
        public static string ViveTool_DownloadProgress {
            get {
                return ResourceManager.GetString("ViveTool_DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        public static string ViveTool_DownloadComplete {
            get {
                return ResourceManager.GetString("ViveTool_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool has been downloaded to {0}.
        /// </summary>
        public static string ViveTool_DownloadCompleteMessage {
            get {
                return ResourceManager.GetString("ViveTool_DownloadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string ViveTool_DownloadFailed {
            get {
                return ResourceManager.GetString("ViveTool_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ViveTool_Refresh {
            get {
                return ResourceManager.GetString("ViveTool_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Features.
        /// </summary>
        public static string ViveTool_SearchFeatures {
            get {
                return ResourceManager.GetString("ViveTool_SearchFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter feature ID or name to search....
        /// </summary>
        public static string ViveTool_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ViveTool_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ViveTool_Search {
            get {
                return ResourceManager.GetString("ViveTool_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Flags.
        /// </summary>
        public static string ViveTool_FeatureFlags {
            get {
                return ResourceManager.GetString("ViveTool_FeatureFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        public static string ViveTool_RefreshList {
            get {
                return ResourceManager.GetString("ViveTool_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ViveTool_Loading {
            get {
                return ResourceManager.GetString("ViveTool_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ViveTool_FeatureId {
            get {
                return ResourceManager.GetString("ViveTool_FeatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ViveTool_FeatureName {
            get {
                return ResourceManager.GetString("ViveTool_FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ViveTool_Status {
            get {
                return ResourceManager.GetString("ViveTool_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ViveTool_Actions {
            get {
                return ResourceManager.GetString("ViveTool_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string ViveTool_Enable {
            get {
                return ResourceManager.GetString("ViveTool_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string ViveTool_Disable {
            get {
                return ResourceManager.GetString("ViveTool_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features found.
        /// </summary>
        public static string ViveTool_NoFeaturesFound {
            get {
                return ResourceManager.GetString("ViveTool_NoFeaturesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Enabled.
        /// </summary>
        public static string ViveTool_FeatureEnabled {
            get {
                return ResourceManager.GetString("ViveTool_FeatureEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} has been enabled successfully.
        /// </summary>
        public static string ViveTool_FeatureEnabledMessage {
            get {
                return ResourceManager.GetString("ViveTool_FeatureEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Disabled.
        /// </summary>
        public static string ViveTool_FeatureDisabled {
            get {
                return ResourceManager.GetString("ViveTool_FeatureDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} has been disabled successfully.
        /// </summary>
        public static string ViveTool_FeatureDisabledMessage {
            get {
                return ResourceManager.GetString("ViveTool_FeatureDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ViveTool_Error {
            get {
                return ResourceManager.GetString("ViveTool_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable feature {0}. Please check administrator permissions..
        /// </summary>
        public static string ViveTool_EnableFeatureFailed {
            get {
                return ResourceManager.GetString("ViveTool_EnableFeatureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable feature {0}. Please check administrator permissions..
        /// </summary>
        public static string ViveTool_DisableFeatureFailed {
            get {
                return ResourceManager.GetString("ViveTool_DisableFeatureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ViveTool_Import {
            get {
                return ResourceManager.GetString("ViveTool_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        public static string ViveTool_ImportFromFile {
            get {
                return ResourceManager.GetString("ViveTool_ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from URL.
        /// </summary>
        public static string ViveTool_ImportFromUrl {
            get {
                return ResourceManager.GetString("ViveTool_ImportFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import feature flags from a file or URL. Supported formats: JSON, CSV, or plain text (one ID per line)..
        /// </summary>
        public static string ViveTool_ImportDescription {
            get {
                return ResourceManager.GetString("ViveTool_ImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL to import feature flags from:.
        /// </summary>
        public static string ViveTool_ImportUrlDescription {
            get {
                return ResourceManager.GetString("ViveTool_ImportUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Successful.
        /// </summary>
        public static string ViveTool_ImportSuccess {
            get {
                return ResourceManager.GetString("ViveTool_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} feature flag(s).
        /// </summary>
        public static string ViveTool_ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ViveTool_ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import features: {0}.
        /// </summary>
        public static string ViveTool_ImportFailed {
            get {
                return ResourceManager.GetString("ViveTool_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL. Please enter a valid URL..
        /// </summary>
        public static string ViveTool_InvalidUrl {
            get {
                return ResourceManager.GetString("ViveTool_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ViveTool_Cancel {
            get {
                return ResourceManager.GetString("ViveTool_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ViveTool_Browse {
            get {
                return ResourceManager.GetString("ViveTool_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vivetool.exe.
        /// </summary>
        public static string ViveTool_SelectViveTool {
            get {
                return ResourceManager.GetString("ViveTool_SelectViveTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vivetool.exe file.
        /// </summary>
        public static string ViveTool_InvalidViveToolFile {
            get {
                return ResourceManager.GetString("ViveTool_InvalidViveToolFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Set.
        /// </summary>
        public static string ViveTool_PathSet {
            get {
                return ResourceManager.GetString("ViveTool_PathSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool path has been set to: {0}.
        /// </summary>
        public static string ViveTool_PathSetMessage {
            get {
                return ResourceManager.GetString("ViveTool_PathSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set ViVeTool path: {0}.
        /// </summary>
        public static string ViveTool_SetPathFailed {
            get {
                return ResourceManager.GetString("ViveTool_SetPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ViveTool_Download {
            get {
                return ResourceManager.GetString("ViveTool_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool.exe Path.
        /// </summary>
        public static string ViveTool_PathPlaceholder {
            get {
                return ResourceManager.GetString("ViveTool_PathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to ViVeTool.exe file. If not specified, built-in download or version in system PATH will be used..
        /// </summary>
        public static string ViveTool_PathDescription {
            get {
                return ResourceManager.GetString("ViveTool_PathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error browsing files: {0}.
        /// </summary>
        public static string ViveTool_BrowseError {
            get {
                return ResourceManager.GetString("ViveTool_BrowseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ViVeTool....
        /// </summary>
        public static string ViveTool_Downloading {
            get {
                return ResourceManager.GetString("ViveTool_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ViveTool_StatusEnabled {
            get {
                return ResourceManager.GetString("ViveTool_StatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ViveTool_StatusDisabled {
            get {
                return ResourceManager.GetString("ViveTool_StatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ViveTool_StatusDefault {
            get {
                return ResourceManager.GetString("ViveTool_StatusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ViveTool_StatusUnknown {
            get {
                return ResourceManager.GetString("ViveTool_StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViVeTool not found. Please configure it in settings..
        /// </summary>
        public static string ViveTool_MissingToolMessage {
            get {
                return ResourceManager.GetString("ViveTool_MissingToolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string ViveTool_GoToSettings {
            get {
                return ResourceManager.GetString("ViveTool_GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Config.
        /// </summary>
        public static string ViveTool_ImportConfig {
            get {
                return ResourceManager.GetString("ViveTool_ImportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Configuration.
        /// </summary>
        public static string ViveTool_ImportConfigTitle {
            get {
                return ResourceManager.GetString("ViveTool_ImportConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ViVeTool configuration from a local file. This will load feature flags and their settings..
        /// </summary>
        public static string ViveTool_ImportConfigDescription {
            get {
                return ResourceManager.GetString("ViveTool_ImportConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Imported.
        /// </summary>
        public static string ViveTool_ConfigImportSuccess {
            get {
                return ResourceManager.GetString("ViveTool_ConfigImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} feature configurations from {1}.
        /// </summary>
        public static string ViveTool_ConfigImportSuccessMessage {
            get {
                return ResourceManager.GetString("ViveTool_ConfigImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        public static string ViveTool_ConfigImportFailed {
            get {
                return ResourceManager.GetString("ViveTool_ConfigImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import configuration: {0}.
        /// </summary>
        public static string ViveTool_ConfigImportFailedMessage {
            get {
                return ResourceManager.GetString("ViveTool_ConfigImportFailedMessage", resourceCulture);
            }
        }
    }
}
